# use collections to realize category
# collections:
  # my_categories:
    # output: true
    # permalink: /blog/category/:name/
  # my_tags:
    # output: true
    # permalink: /blog/tag/:name/
    
#sidebar names
sidebar:
  home:              主页
  about:             关于我
  following:         文章搜集
  books:             读书笔记

# Permalinks
#permalink:           pretty

# Conversion
markdown:    kramdown
highlighter: rouge
excerpt_separator: "\n\n\n"

# Setup
title:               Victor
name:                victor-infosec
namecn:              victor-infosec
tagline:             'cybersecurity'
description:         "Victor's blog"
url:                 https://victor-infosec.github.io
baseurl:             ''
gems:
  - jekyll-feed
  - jekyll-seo-tag

# About/contact
author:
  name:              Victor
  url:               https://victor-infosec.github.io
  email:             victor_xxx@yeah.net

sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: blog_by_category
  
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: blog_by_tag
    
# Custom vars
version:             1.0.0

paginate: 5
paginate_path: "/blog/category/following/page:num"

paginatepath: ['/page:num',]
